title:             Seoksu's Blog
email:             blindsage10@gmail.com / blindsage10@naver.com
description:       A Blog for Statistical Life
author:            Seoksu Hong
baseurl:           
url:               

# Social Profiles
twitter_username:  blindsage10
github_username:   blindsage10
facebook_username: blindsage10

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
